In [1]:
import numpy as np

# Define the matrix
A = np.array([[1, 2, 1], [-2, 3, 2]])

# Perform SVD
U, s, VT = np.linalg.svd(A)

# Create a sigma matrix with the correct dimensions (2x3)
Sigma = np.zeros((2, 3))
Sigma[0, 0], Sigma[1, 1] = s[0], s[1]

# Multiplying U, Sigma, and V^T
A_reconstructed = np.dot(U, np.dot(Sigma, VT))

# Display the results
print("U matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV^T (V Transpose) matrix:")
print(VT)
print("\nReconstructed A matrix from U, Sigma, and V^T:")
print(A_reconstructed)

U matrix:
[[-0.40266324 -0.91534819]
 [-0.91534819  0.40266324]]

Sigma matrix:
[[4.43163743 0.         0.        ]
 [0.         1.83319113 0.        ]]

V^T (V Transpose) matrix:
[[ 0.32223601 -0.80136769 -0.50395811]
 [-0.93862263 -0.33968453 -0.0600165 ]
 [ 0.12309149 -0.49236596  0.86164044]]

Reconstructed A matrix from U, Sigma, and V^T:
[[ 1.  2.  1.]
 [-2.  3.  2.]]


In [2]:
import numpy as np

# Define the matrix
A = np.array([[1, 2, 1], [-2, 3, 2]])

# Perform SVD
U, S, VT = np.linalg.svd(A)

# Multiplying U, Sigma, and V^T
A_reconstructed = np.dot(U, np.dot(Sigma, VT))

# Print the U, S, V^T and Reconstructed A matrices
print("U matrix:")
print(U)
print("\nSigma matrix:")
print(np.diag(S))
print("\nV^T (V Transpose) matrix:")
print(VT)
print("\nReconstructed A matrix from U, Sigma, and V^T:")
print(A_reconstructed)

U matrix:
[[-0.40266324 -0.91534819]
 [-0.91534819  0.40266324]]

Sigma matrix:
[[4.43163743 0.        ]
 [0.         1.83319113]]

V^T (V Transpose) matrix:
[[ 0.32223601 -0.80136769 -0.50395811]
 [-0.93862263 -0.33968453 -0.0600165 ]
 [ 0.12309149 -0.49236596  0.86164044]]

Reconstructed A matrix from U, Sigma, and V^T:
[[ 1.  2.  1.]
 [-2.  3.  2.]]
